"""commit 18/02/2025

Revision ID: 0813a9b4b30f
Revises: 7afd59ab66de
Create Date: 2025-02-18 16:59:13.728736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0813a9b4b30f'
down_revision: Union[str, None] = '7afd59ab66de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
