"""3

Revision ID: 4b0777b71a1a
Revises: 0040195ed59f
Create Date: 2025-03-19 10:30:54.954726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b0777b71a1a'
down_revision: Union[str, None] = '0040195ed59f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacientes', sa.Column('cpf', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_pacientes_cpf'), 'pacientes', ['cpf'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pacientes_cpf'), table_name='pacientes')
    op.drop_column('pacientes', 'cpf')
    # ### end Alembic commands ###
