"""adiciona funcionarioEspecialidade

Revision ID: 51c07f1c3f7d
Revises: 97ccecdf3521
Create Date: 2025-04-29 14:16:14.426599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51c07f1c3f7d'
down_revision: Union[str, None] = '97ccecdf3521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funcionario_especialidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_funcionario', sa.Integer(), nullable=False),
    sa.Column('fk_especialidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_especialidade'], ['especialidades.id'], ),
    sa.ForeignKeyConstraint(['fk_funcionario'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funcionario_especialidades_fk_especialidade'), 'funcionario_especialidades', ['fk_especialidade'], unique=False)
    op.create_index(op.f('ix_funcionario_especialidades_fk_funcionario'), 'funcionario_especialidades', ['fk_funcionario'], unique=False)
    op.create_index(op.f('ix_funcionario_especialidades_id'), 'funcionario_especialidades', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_funcionario_especialidades_id'), table_name='funcionario_especialidades')
    op.drop_index(op.f('ix_funcionario_especialidades_fk_funcionario'), table_name='funcionario_especialidades')
    op.drop_index(op.f('ix_funcionario_especialidades_fk_especialidade'), table_name='funcionario_especialidades')
    op.drop_table('funcionario_especialidades')
    # ### end Alembic commands ###
