"""Descrição da mudança

Revision ID: 54497f7c7681
Revises: 
Create Date: 2025-01-26 14:28:12.098806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54497f7c7681'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especialidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_especialidades_id'), 'especialidades', ['id'], unique=False)
    op.create_table('exames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('resultado', sa.String(length=500), nullable=True),
    sa.Column('data_realizacao', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exames_id'), 'exames', ['id'], unique=False)
    op.create_table('medicamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('info', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicamentos_id'), 'medicamentos', ['id'], unique=False)
    op.create_table('pacientes',
    sa.Column('numeroSUS', sa.Integer(), nullable=False),
    sa.Column('dataNascimento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.String(length=255), nullable=True),
    sa.Column('info', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('microRegiao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('numeroSUS')
    )
    op.create_index(op.f('ix_pacientes_email'), 'pacientes', ['email'], unique=False)
    op.create_index(op.f('ix_pacientes_info'), 'pacientes', ['info'], unique=False)
    op.create_index(op.f('ix_pacientes_microRegiao'), 'pacientes', ['microRegiao'], unique=False)
    op.create_index(op.f('ix_pacientes_nome'), 'pacientes', ['nome'], unique=False)
    op.create_index(op.f('ix_pacientes_numeroSUS'), 'pacientes', ['numeroSUS'], unique=False)
    op.create_index(op.f('ix_pacientes_sexo'), 'pacientes', ['sexo'], unique=False)
    op.create_index(op.f('ix_pacientes_telefone'), 'pacientes', ['telefone'], unique=False)
    op.create_table('patologia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patologia_id'), 'patologia', ['id'], unique=False)
    op.create_table('perfis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perfis_id'), 'perfis', ['id'], unique=False)
    op.create_index(op.f('ix_perfis_name'), 'perfis', ['name'], unique=True)
    op.create_table('permissoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissoes_id'), 'permissoes', ['id'], unique=False)
    op.create_index(op.f('ix_permissoes_name'), 'permissoes', ['name'], unique=True)
    op.create_table('biometrias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imc', sa.Float(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('altura', sa.Float(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('cintura', sa.Float(), nullable=False),
    sa.Column('paciente_i', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paciente_i'], ['pacientes.numeroSUS'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biometrias_id'), 'biometrias', ['id'], unique=False)
    op.create_table('consultas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('FkPaciente', sa.Integer(), nullable=False),
    sa.Column('FkEspecialidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['FkEspecialidade'], ['especialidades.id'], ),
    sa.ForeignKeyConstraint(['FkPaciente'], ['pacientes.numeroSUS'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultas_FkEspecialidade'), 'consultas', ['FkEspecialidade'], unique=False)
    op.create_index(op.f('ix_consultas_FkPaciente'), 'consultas', ['FkPaciente'], unique=False)
    op.create_index(op.f('ix_consultas_id'), 'consultas', ['id'], unique=False)
    op.create_table('findrisk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('pont_historico_familiar_de_diabetes', sa.String(length=255), nullable=True),
    sa.Column('pont_historico_de_glicemia_elevada', sa.String(length=255), nullable=True),
    sa.Column('classificacao', sa.String(length=255), nullable=True),
    sa.Column('pont_idade', sa.String(length=255), nullable=True),
    sa.Column('pont_imc', sa.String(length=255), nullable=True),
    sa.Column('pont_circuferencia_cintura', sa.String(length=255), nullable=True),
    sa.Column('pont_atv_fisica', sa.String(length=255), nullable=True),
    sa.Column('pont_ingestao_frutas_e_verduras', sa.String(length=255), nullable=True),
    sa.Column('pont_hipertensao', sa.String(length=255), nullable=True),
    sa.Column('FkPaciente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['FkPaciente'], ['pacientes.numeroSUS'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findrisk_id'), 'findrisk', ['id'], unique=False)
    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('idPerfil', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idPerfil'], ['perfis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funcionarios_cpf'), 'funcionarios', ['cpf'], unique=True)
    op.create_index(op.f('ix_funcionarios_email'), 'funcionarios', ['email'], unique=True)
    op.create_index(op.f('ix_funcionarios_id'), 'funcionarios', ['id'], unique=False)
    op.create_index(op.f('ix_funcionarios_idPerfil'), 'funcionarios', ['idPerfil'], unique=False)
    op.create_index(op.f('ix_funcionarios_nome'), 'funcionarios', ['nome'], unique=True)
    op.create_table('paciente_patologias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FkPatologia', sa.Integer(), nullable=False),
    sa.Column('Fkpaciente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['FkPatologia'], ['patologia.id'], ),
    sa.ForeignKeyConstraint(['Fkpaciente'], ['pacientes.numeroSUS'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paciente_patologias_id'), 'paciente_patologias', ['id'], unique=False)
    op.create_table('perfilpermissoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idPerfil', sa.Integer(), nullable=False),
    sa.Column('idPermissao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idPerfil'], ['perfis.id'], ),
    sa.ForeignKeyConstraint(['idPermissao'], ['permissoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perfilpermissoes_id'), 'perfilpermissoes', ['id'], unique=False)
    op.create_index(op.f('ix_perfilpermissoes_idPerfil'), 'perfilpermissoes', ['idPerfil'], unique=False)
    op.create_index(op.f('ix_perfilpermissoes_idPermissao'), 'perfilpermissoes', ['idPermissao'], unique=False)
    op.create_table('prescricoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.Date(), nullable=False),
    sa.Column('fim', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('frequencia', sa.String(length=255), nullable=False),
    sa.Column('dosagem', sa.String(length=255), nullable=False),
    sa.Column('fk_medicamento', sa.Integer(), nullable=False),
    sa.Column('Fkpaciente', sa.Integer(), nullable=False),
    sa.Column('fk_exame', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Fkpaciente'], ['pacientes.numeroSUS'], ),
    sa.ForeignKeyConstraint(['fk_exame'], ['exames.id'], ),
    sa.ForeignKeyConstraint(['fk_medicamento'], ['medicamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescricoes_id'), 'prescricoes', ['id'], unique=False)
    op.create_table('retornos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FkPaciente', sa.Integer(), nullable=False),
    sa.Column('FkEspecialidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['FkEspecialidade'], ['especialidades.id'], ),
    sa.ForeignKeyConstraint(['FkPaciente'], ['pacientes.numeroSUS'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retornos_FkEspecialidade'), 'retornos', ['FkEspecialidade'], unique=False)
    op.create_index(op.f('ix_retornos_FkPaciente'), 'retornos', ['FkPaciente'], unique=False)
    op.create_index(op.f('ix_retornos_id'), 'retornos', ['id'], unique=False)
    op.create_table('funcionariosEspecialidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FkFuncionario', sa.Integer(), nullable=False),
    sa.Column('FkEspecialidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['FkEspecialidade'], ['especialidades.id'], ),
    sa.ForeignKeyConstraint(['FkFuncionario'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funcionariosEspecialidades_FkEspecialidade'), 'funcionariosEspecialidades', ['FkEspecialidade'], unique=False)
    op.create_index(op.f('ix_funcionariosEspecialidades_FkFuncionario'), 'funcionariosEspecialidades', ['FkFuncionario'], unique=False)
    op.create_index(op.f('ix_funcionariosEspecialidades_id'), 'funcionariosEspecialidades', ['id'], unique=False)
    op.create_table('prontuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fkfuncionarioespecialidade', sa.Integer(), nullable=False),
    sa.Column('fkpaciente', sa.Integer(), nullable=False),
    sa.Column('fkexame', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fkexame'], ['exames.id'], ),
    sa.ForeignKeyConstraint(['fkfuncionarioespecialidade'], ['funcionariosEspecialidades.id'], ),
    sa.ForeignKeyConstraint(['fkpaciente'], ['pacientes.numeroSUS'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prontuarios_fkfuncionarioespecialidade'), 'prontuarios', ['fkfuncionarioespecialidade'], unique=False)
    op.create_index(op.f('ix_prontuarios_id'), 'prontuarios', ['id'], unique=False)
    op.create_table('estratificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('categoria', sa.String(length=255), nullable=False),
    sa.Column('FkProntuario', sa.Integer(), nullable=False),
    sa.Column('FkPaciente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['FkPaciente'], ['pacientes.numeroSUS'], ),
    sa.ForeignKeyConstraint(['FkProntuario'], ['prontuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estratificacoes_id'), 'estratificacoes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estratificacoes_id'), table_name='estratificacoes')
    op.drop_table('estratificacoes')
    op.drop_index(op.f('ix_prontuarios_id'), table_name='prontuarios')
    op.drop_index(op.f('ix_prontuarios_fkfuncionarioespecialidade'), table_name='prontuarios')
    op.drop_table('prontuarios')
    op.drop_index(op.f('ix_funcionariosEspecialidades_id'), table_name='funcionariosEspecialidades')
    op.drop_index(op.f('ix_funcionariosEspecialidades_FkFuncionario'), table_name='funcionariosEspecialidades')
    op.drop_index(op.f('ix_funcionariosEspecialidades_FkEspecialidade'), table_name='funcionariosEspecialidades')
    op.drop_table('funcionariosEspecialidades')
    op.drop_index(op.f('ix_retornos_id'), table_name='retornos')
    op.drop_index(op.f('ix_retornos_FkPaciente'), table_name='retornos')
    op.drop_index(op.f('ix_retornos_FkEspecialidade'), table_name='retornos')
    op.drop_table('retornos')
    op.drop_index(op.f('ix_prescricoes_id'), table_name='prescricoes')
    op.drop_table('prescricoes')
    op.drop_index(op.f('ix_perfilpermissoes_idPermissao'), table_name='perfilpermissoes')
    op.drop_index(op.f('ix_perfilpermissoes_idPerfil'), table_name='perfilpermissoes')
    op.drop_index(op.f('ix_perfilpermissoes_id'), table_name='perfilpermissoes')
    op.drop_table('perfilpermissoes')
    op.drop_index(op.f('ix_paciente_patologias_id'), table_name='paciente_patologias')
    op.drop_table('paciente_patologias')
    op.drop_index(op.f('ix_funcionarios_nome'), table_name='funcionarios')
    op.drop_index(op.f('ix_funcionarios_idPerfil'), table_name='funcionarios')
    op.drop_index(op.f('ix_funcionarios_id'), table_name='funcionarios')
    op.drop_index(op.f('ix_funcionarios_email'), table_name='funcionarios')
    op.drop_index(op.f('ix_funcionarios_cpf'), table_name='funcionarios')
    op.drop_table('funcionarios')
    op.drop_index(op.f('ix_findrisk_id'), table_name='findrisk')
    op.drop_table('findrisk')
    op.drop_index(op.f('ix_consultas_id'), table_name='consultas')
    op.drop_index(op.f('ix_consultas_FkPaciente'), table_name='consultas')
    op.drop_index(op.f('ix_consultas_FkEspecialidade'), table_name='consultas')
    op.drop_table('consultas')
    op.drop_index(op.f('ix_biometrias_id'), table_name='biometrias')
    op.drop_table('biometrias')
    op.drop_index(op.f('ix_permissoes_name'), table_name='permissoes')
    op.drop_index(op.f('ix_permissoes_id'), table_name='permissoes')
    op.drop_table('permissoes')
    op.drop_index(op.f('ix_perfis_name'), table_name='perfis')
    op.drop_index(op.f('ix_perfis_id'), table_name='perfis')
    op.drop_table('perfis')
    op.drop_index(op.f('ix_patologia_id'), table_name='patologia')
    op.drop_table('patologia')
    op.drop_index(op.f('ix_pacientes_telefone'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_sexo'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_numeroSUS'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_nome'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_microRegiao'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_info'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_email'), table_name='pacientes')
    op.drop_table('pacientes')
    op.drop_index(op.f('ix_medicamentos_id'), table_name='medicamentos')
    op.drop_table('medicamentos')
    op.drop_index(op.f('ix_exames_id'), table_name='exames')
    op.drop_table('exames')
    op.drop_index(op.f('ix_especialidades_id'), table_name='especialidades')
    op.drop_table('especialidades')
    # ### end Alembic commands ###
