"""commit 2

Revision ID: 7afd59ab66de
Revises: a5226a335219
Create Date: 2025-02-18 10:04:04.864919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7afd59ab66de'
down_revision: Union[str, None] = 'a5226a335219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultas', sa.Column('data', sa.Date(), nullable=True))
    op.add_column('consultas', sa.Column('status', sa.Integer(), nullable=False))
    op.add_column('consultas', sa.Column('observacoes', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'consultas', ['observacoes'])
    op.alter_column('exames', 'data_realizacao',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Date(),
               existing_nullable=False)
    op.add_column('pacientes', sa.Column('cpf', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_pacientes_cpf'), 'pacientes', ['cpf'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pacientes_cpf'), table_name='pacientes')
    op.drop_column('pacientes', 'cpf')
    op.alter_column('exames', 'data_realizacao',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(None, 'consultas', type_='unique')
    op.drop_column('consultas', 'observacoes')
    op.drop_column('consultas', 'status')
    op.drop_column('consultas', 'data')
    # ### end Alembic commands ###
