"""Adiciona campo icon em patologia

Revision ID: 9174e901c008
Revises: 51c07f1c3f7d
Create Date: 2025-05-20 07:48:22.212094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9174e901c008'
down_revision: Union[str, None] = '51c07f1c3f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pacientes_cpf', table_name='pacientes')
    op.create_index(op.f('ix_pacientes_cpf'), 'pacientes', ['cpf'], unique=True)
    op.drop_index('ix_pacientes_email', table_name='pacientes')
    op.create_index(op.f('ix_pacientes_email'), 'pacientes', ['email'], unique=True)
    op.add_column('patologia', sa.Column('icon', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patologia', 'icon')
    op.drop_index(op.f('ix_pacientes_email'), table_name='pacientes')
    op.create_index('ix_pacientes_email', 'pacientes', ['email'], unique=False)
    op.drop_index(op.f('ix_pacientes_cpf'), table_name='pacientes')
    op.create_index('ix_pacientes_cpf', 'pacientes', ['cpf'], unique=False)
    # ### end Alembic commands ###
