"""01/04/2025

Revision ID: 97ccecdf3521
Revises: 8df649ee876c
Create Date: 2025-04-01 10:38:34.978961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97ccecdf3521'
down_revision: Union[str, None] = '8df649ee876c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultas', sa.Column('data', sa.Date(), nullable=True))
    op.add_column('consultas', sa.Column('status', sa.Integer(), nullable=False))
    op.add_column('consultas', sa.Column('observacoes', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultas', 'observacoes')
    op.drop_column('consultas', 'status')
    op.drop_column('consultas', 'data')
    # ### end Alembic commands ###
