"""commit 1

Revision ID: fbb1524d42c9
Revises: 
Create Date: 2025-02-07 16:17:19.390563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbb1524d42c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especialidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_especialidades_id'), 'especialidades', ['id'], unique=False)
    op.create_table('pacientes',
    sa.Column('numeroSUS', sa.Integer(), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.String(length=255), nullable=True),
    sa.Column('info', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('micro_regiao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('numeroSUS')
    )
    op.create_index(op.f('ix_pacientes_email'), 'pacientes', ['email'], unique=False)
    op.create_index(op.f('ix_pacientes_info'), 'pacientes', ['info'], unique=False)
    op.create_index(op.f('ix_pacientes_micro_regiao'), 'pacientes', ['micro_regiao'], unique=False)
    op.create_index(op.f('ix_pacientes_nome'), 'pacientes', ['nome'], unique=False)
    op.create_index(op.f('ix_pacientes_numeroSUS'), 'pacientes', ['numeroSUS'], unique=False)
    op.create_index(op.f('ix_pacientes_sexo'), 'pacientes', ['sexo'], unique=False)
    op.create_index(op.f('ix_pacientes_telefone'), 'pacientes', ['telefone'], unique=False)
    op.create_table('patologia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patologia_id'), 'patologia', ['id'], unique=False)
    op.create_table('perfis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perfis_id'), 'perfis', ['id'], unique=False)
    op.create_index(op.f('ix_perfis_name'), 'perfis', ['name'], unique=True)
    op.create_table('permissoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissoes_id'), 'permissoes', ['id'], unique=False)
    op.create_index(op.f('ix_permissoes_name'), 'permissoes', ['name'], unique=True)
    op.create_table('tipos_exames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_exames_id'), 'tipos_exames', ['id'], unique=False)
    op.create_table('tipos_medicamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('info', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_medicamentos_id'), 'tipos_medicamentos', ['id'], unique=False)
    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('id_perfil', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_perfil'], ['perfis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funcionarios_cpf'), 'funcionarios', ['cpf'], unique=True)
    op.create_index(op.f('ix_funcionarios_email'), 'funcionarios', ['email'], unique=True)
    op.create_index(op.f('ix_funcionarios_id'), 'funcionarios', ['id'], unique=False)
    op.create_index(op.f('ix_funcionarios_id_perfil'), 'funcionarios', ['id_perfil'], unique=False)
    op.create_index(op.f('ix_funcionarios_nome'), 'funcionarios', ['nome'], unique=True)
    op.create_table('paciente_patologias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_patologia', sa.Integer(), nullable=False),
    sa.Column('fk_paciente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_paciente'], ['pacientes.numeroSUS'], ),
    sa.ForeignKeyConstraint(['fk_patologia'], ['patologia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paciente_patologias_id'), 'paciente_patologias', ['id'], unique=False)
    op.create_table('perfilpermissoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_perfil', sa.Integer(), nullable=False),
    sa.Column('id_permissao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_perfil'], ['perfis.id'], ),
    sa.ForeignKeyConstraint(['id_permissao'], ['permissoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perfilpermissoes_id'), 'perfilpermissoes', ['id'], unique=False)
    op.create_index(op.f('ix_perfilpermissoes_id_perfil'), 'perfilpermissoes', ['id_perfil'], unique=False)
    op.create_index(op.f('ix_perfilpermissoes_id_permissao'), 'perfilpermissoes', ['id_permissao'], unique=False)
    op.create_table('consultas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fk_paciente', sa.Integer(), nullable=False),
    sa.Column('fk_especialidade', sa.Integer(), nullable=False),
    sa.Column('fk_funcionario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_especialidade'], ['especialidades.id'], ),
    sa.ForeignKeyConstraint(['fk_funcionario'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['fk_paciente'], ['pacientes.numeroSUS'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultas_fk_especialidade'), 'consultas', ['fk_especialidade'], unique=False)
    op.create_index(op.f('ix_consultas_fk_funcionario'), 'consultas', ['fk_funcionario'], unique=False)
    op.create_index(op.f('ix_consultas_fk_paciente'), 'consultas', ['fk_paciente'], unique=False)
    op.create_index(op.f('ix_consultas_id'), 'consultas', ['id'], unique=False)
    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('ip_origem', sa.String(length=255), nullable=False),
    sa.Column('acao', sa.String(length=255), nullable=False),
    sa.Column('tabela_afetada', sa.String(length=255), nullable=True),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('detalhes_erro', sa.String(length=255), nullable=True),
    sa.Column('origem', sa.String(length=255), nullable=False),
    sa.Column('metodo_http', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_id'), 'logs', ['id'], unique=False)
    op.create_table('biometrias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imc', sa.Float(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('altura', sa.Float(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('cintura', sa.Float(), nullable=False),
    sa.Column('fk_paciente', sa.Integer(), nullable=False),
    sa.Column('fk_consulta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_consulta'], ['consultas.id'], ),
    sa.ForeignKeyConstraint(['fk_paciente'], ['pacientes.numeroSUS'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biometrias_id'), 'biometrias', ['id'], unique=False)
    op.create_table('estratificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('categoria', sa.String(length=255), nullable=False),
    sa.Column('fk_paciente', sa.Integer(), nullable=False),
    sa.Column('fk_consulta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_consulta'], ['consultas.id'], ),
    sa.ForeignKeyConstraint(['fk_paciente'], ['pacientes.numeroSUS'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estratificacoes_id'), 'estratificacoes', ['id'], unique=False)
    op.create_table('exames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_realizacao', sa.String(length=50), nullable=False),
    sa.Column('resultado', sa.String(length=500), nullable=True),
    sa.Column('fk_paciente', sa.Integer(), nullable=False),
    sa.Column('fk_tipo_exame', sa.Integer(), nullable=False),
    sa.Column('fk_consulta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_consulta'], ['consultas.id'], ),
    sa.ForeignKeyConstraint(['fk_paciente'], ['pacientes.numeroSUS'], ),
    sa.ForeignKeyConstraint(['fk_tipo_exame'], ['tipos_exames.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exames_id'), 'exames', ['id'], unique=False)
    op.create_table('findrisk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('pont_historico_familiar_de_diabetes', sa.String(length=255), nullable=True),
    sa.Column('pont_historico_de_glicemia_elevada', sa.String(length=255), nullable=True),
    sa.Column('classificacao', sa.String(length=255), nullable=True),
    sa.Column('pont_idade', sa.String(length=255), nullable=True),
    sa.Column('pont_imc', sa.String(length=255), nullable=True),
    sa.Column('pont_circunferencia_cintura', sa.String(length=255), nullable=True),
    sa.Column('pont_atv_fisica', sa.String(length=255), nullable=True),
    sa.Column('pont_ingestao_frutas_e_verduras', sa.String(length=255), nullable=True),
    sa.Column('pont_hipertensao', sa.String(length=255), nullable=True),
    sa.Column('fk_paciente', sa.Integer(), nullable=False),
    sa.Column('fk_consulta', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_consulta'], ['consultas.id'], ),
    sa.ForeignKeyConstraint(['fk_paciente'], ['pacientes.numeroSUS'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findrisk_id'), 'findrisk', ['id'], unique=False)
    op.create_table('medicamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('frequencia', sa.String(length=255), nullable=False),
    sa.Column('dosagem', sa.String(length=255), nullable=False),
    sa.Column('fk_tipo_medicamento', sa.Integer(), nullable=False),
    sa.Column('fk_paciente', sa.Integer(), nullable=False),
    sa.Column('fk_consulta', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_consulta'], ['consultas.id'], ),
    sa.ForeignKeyConstraint(['fk_paciente'], ['pacientes.numeroSUS'], ),
    sa.ForeignKeyConstraint(['fk_tipo_medicamento'], ['tipos_medicamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicamentos_id'), 'medicamentos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medicamentos_id'), table_name='medicamentos')
    op.drop_table('medicamentos')
    op.drop_index(op.f('ix_findrisk_id'), table_name='findrisk')
    op.drop_table('findrisk')
    op.drop_index(op.f('ix_exames_id'), table_name='exames')
    op.drop_table('exames')
    op.drop_index(op.f('ix_estratificacoes_id'), table_name='estratificacoes')
    op.drop_table('estratificacoes')
    op.drop_index(op.f('ix_biometrias_id'), table_name='biometrias')
    op.drop_table('biometrias')
    op.drop_index(op.f('ix_logs_id'), table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_consultas_id'), table_name='consultas')
    op.drop_index(op.f('ix_consultas_fk_paciente'), table_name='consultas')
    op.drop_index(op.f('ix_consultas_fk_funcionario'), table_name='consultas')
    op.drop_index(op.f('ix_consultas_fk_especialidade'), table_name='consultas')
    op.drop_table('consultas')
    op.drop_index(op.f('ix_perfilpermissoes_id_permissao'), table_name='perfilpermissoes')
    op.drop_index(op.f('ix_perfilpermissoes_id_perfil'), table_name='perfilpermissoes')
    op.drop_index(op.f('ix_perfilpermissoes_id'), table_name='perfilpermissoes')
    op.drop_table('perfilpermissoes')
    op.drop_index(op.f('ix_paciente_patologias_id'), table_name='paciente_patologias')
    op.drop_table('paciente_patologias')
    op.drop_index(op.f('ix_funcionarios_nome'), table_name='funcionarios')
    op.drop_index(op.f('ix_funcionarios_id_perfil'), table_name='funcionarios')
    op.drop_index(op.f('ix_funcionarios_id'), table_name='funcionarios')
    op.drop_index(op.f('ix_funcionarios_email'), table_name='funcionarios')
    op.drop_index(op.f('ix_funcionarios_cpf'), table_name='funcionarios')
    op.drop_table('funcionarios')
    op.drop_index(op.f('ix_tipos_medicamentos_id'), table_name='tipos_medicamentos')
    op.drop_table('tipos_medicamentos')
    op.drop_index(op.f('ix_tipos_exames_id'), table_name='tipos_exames')
    op.drop_table('tipos_exames')
    op.drop_index(op.f('ix_permissoes_name'), table_name='permissoes')
    op.drop_index(op.f('ix_permissoes_id'), table_name='permissoes')
    op.drop_table('permissoes')
    op.drop_index(op.f('ix_perfis_name'), table_name='perfis')
    op.drop_index(op.f('ix_perfis_id'), table_name='perfis')
    op.drop_table('perfis')
    op.drop_index(op.f('ix_patologia_id'), table_name='patologia')
    op.drop_table('patologia')
    op.drop_index(op.f('ix_pacientes_telefone'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_sexo'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_numeroSUS'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_nome'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_micro_regiao'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_info'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_email'), table_name='pacientes')
    op.drop_table('pacientes')
    op.drop_index(op.f('ix_especialidades_id'), table_name='especialidades')
    op.drop_table('especialidades')
    # ### end Alembic commands ###
